# Generated by Django 4.2.21 on 2025-07-31 03:31

import apptimtruonghoc.models
import ckeditor.fields
from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254,
                        unique=True,
                        verbose_name="Email (Tên đăng nhập)",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="Họ"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="Tên"
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="Ngày tháng năm sinh"
                    ),
                ),
                (
                    "living_place",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Nơi sống"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Quản trị viên"),
                            ("staff", "Nhân viên"),
                            ("partner", "Đối tác"),
                            ("regular_user", "Người dùng thông thường"),
                        ],
                        default="regular_user",
                        max_length=20,
                        verbose_name="Vai trò",
                    ),
                ),
                (
                    "user_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("primary", "Tiểu học"),
                            ("secondary", "Trung học cơ sở"),
                            ("highschool", "Trung học phổ thông"),
                            ("university", "Đại học"),
                            ("postgraduate", "Sau đại học"),
                            ("other", "Khác"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Cấp học (Người dùng)",
                    ),
                ),
                (
                    "is_active_user",
                    models.BooleanField(
                        default=True, verbose_name="Trạng thái tài khoản"
                    ),
                ),
                (
                    "user_photo",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Ảnh đại diện",
                    ),
                ),
                ("password", models.CharField(max_length=255, verbose_name="Mật khẩu")),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="apptimtruonghoc_user_set",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="apptimtruonghoc_user_permissions_set",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Người dùng",
                "verbose_name_plural": "Người dùng",
            },
            managers=[
                ("objects", apptimtruonghoc.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Tên Album")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Mô tả Album"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
            ],
            options={
                "verbose_name_plural": "Album ảnh",
            },
        ),
        migrations.CreateModel(
            name="FieldGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Mã lĩnh vực",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Tên lĩnh vực",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        blank=True, null=True, verbose_name="Mô tả"
                    ),
                ),
                (
                    "cover",
                    models.CharField(
                        blank=True, max_length=1000, null=True, verbose_name="Ảnh bìa"
                    ),
                ),
            ],
            options={
                "verbose_name": "Nhóm lĩnh vực",
                "verbose_name_plural": "Các nhóm lĩnh vực",
            },
        ),
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="admin_profile",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "create",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày tạo"),
                ),
            ],
            options={
                "verbose_name": "Quản trị viên",
                "verbose_name_plural": "Quản trị viên",
            },
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="staff_profile",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "create",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày vào làm"),
                ),
            ],
            options={
                "verbose_name": "Nhân viên",
                "verbose_name_plural": "Nhân viên",
            },
        ),
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        max_length=255, verbose_name="Tên trường tiếng Anh"
                    ),
                ),
                (
                    "name_vn",
                    models.CharField(
                        max_length=255, verbose_name="Tên trường tiếng Việt"
                    ),
                ),
                (
                    "short_code",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Mã trường viết tắt",
                    ),
                ),
                (
                    "admission_code",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Mã trường tuyển sinh",
                    ),
                ),
                (
                    "logo",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Logo"
                    ),
                ),
                (
                    "cover_photo",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Ảnh bìa"
                    ),
                ),
                (
                    "established_year",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Năm thành lập"
                    ),
                ),
                (
                    "school_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("public", "Công lập"),
                            ("private", "Ngoài công lập"),
                            ("international", "Quốc tế"),
                        ],
                        default="public",
                        max_length=20,
                        null=True,
                        verbose_name="Loại trường",
                    ),
                ),
                (
                    "website_url",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Đường dẫn website",
                    ),
                ),
                (
                    "quota_per_year",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Chỉ tiêu/năm"
                    ),
                ),
                (
                    "introduction",
                    ckeditor.fields.RichTextField(
                        blank=True, null=True, verbose_name="Giới thiệu trường"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Số điện thoại hotline",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        unique=True,
                        verbose_name="Email",
                    ),
                ),
                (
                    "map_link",
                    models.CharField(
                        blank=True,
                        max_length=1500,
                        null=True,
                        verbose_name="Link bản đồ",
                    ),
                ),
                (
                    "scholarships",
                    ckeditor.fields.RichTextField(
                        blank=True, null=True, verbose_name="Học bổng"
                    ),
                ),
                (
                    "start",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Học phí tối thiểu"
                    ),
                ),
                (
                    "end",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Học phí tối đa"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Khu vực"
                    ),
                ),
                (
                    "address",
                    ckeditor.fields.RichTextField(
                        blank=True,
                        null=True,
                        verbose_name="Địa chỉ các cơ sở của trường",
                    ),
                ),
                (
                    "registration",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        null=True,
                        verbose_name="Đã đăng ký quảng cáo",
                    ),
                ),
                (
                    "tag",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("outstanding", "Nổi bật"),
                            ("pro", "Chuyên nghiệp"),
                            ("new", "Tin mới"),
                            ("urgency", "Tuyến sinh gấp"),
                            ("none", "Bình thường"),
                        ],
                        default="none",
                        max_length=500,
                        null=True,
                        verbose_name="Danh mục",
                    ),
                ),
                (
                    "school_level",
                    models.CharField(
                        choices=[
                            ("college", "Cao đẳng"),
                            ("university", "Đại học"),
                            ("vocational", "Trung cấp"),
                        ],
                        max_length=20,
                        verbose_name="Loại trường (cấp học)",
                    ),
                ),
                (
                    "benchmark_min",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Điểm chuẩn tối thiểu của trường tại năm gần nhất",
                    ),
                ),
                (
                    "socialmedialink",
                    ckeditor.fields.RichTextField(
                        blank=True, null=True, verbose_name="Đường dẫn các trang MXH"
                    ),
                ),
                (
                    "benchmark_max",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Điểm chuẩn tối đa của trường tại năm gần nhất",
                    ),
                ),
                (
                    "album",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="school_linked_to_this_album",
                        to="apptimtruonghoc.album",
                        verbose_name="Album ảnh của trường",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trường học",
                "verbose_name_plural": "Các trường học",
            },
        ),
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Số điện thoại liên hệ đối tác",
                    ),
                ),
                (
                    "contract_start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Ngày bắt đầu hợp đồng"
                    ),
                ),
                (
                    "contract_end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Ngày kết thúc hợp đồng"
                    ),
                ),
                (
                    "contract_details",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Chi tiết hợp đồng",
                    ),
                ),
                (
                    "is_active_partner",
                    models.BooleanField(
                        default=True, verbose_name="Đối tác đang hoạt động"
                    ),
                ),
                (
                    "school",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partner_info",
                        to="apptimtruonghoc.school",
                        verbose_name="Trường đối tác",
                    ),
                ),
            ],
            options={
                "verbose_name": "Đối tác (Trường học)",
                "verbose_name_plural": "Các đối tác (Trường học)",
            },
        ),
        migrations.CreateModel(
            name="Major",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("major_id", models.CharField(max_length=100, verbose_name="Mã ngành")),
                ("name", models.CharField(max_length=190, verbose_name="Tên ngành")),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        blank=True, null=True, verbose_name="Mô tả ngành"
                    ),
                ),
                (
                    "entry_requirement",
                    ckeditor.fields.RichTextField(
                        blank=True, null=True, verbose_name="Phương thức xét tuyển"
                    ),
                ),
                (
                    "min_tuition_fee_per_year",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Học phí tối thiểu ngành/năm",
                    ),
                ),
                (
                    "max_tuition_fee_per_year",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Học phí tối đa ngành/năm",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Đang hoạt động"),
                            ("inactive", "Ngừng hoạt động"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("outstanding", "Nổi bật"),
                            ("pro", "Chuyên nghiệp"),
                            ("none", "Bình thường"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="Tags",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="school_major",
                        to="apptimtruonghoc.school",
                        verbose_name="Thuộc trường",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ngành riêng của từng trường",
                "verbose_name_plural": "Các ngành riêng cho từng trường",
                "unique_together": {("name", "major_id", "school")},
            },
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image_file",
                    models.CharField(max_length=500, verbose_name="Đường dẫn ảnh"),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Chú thích"
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Ngày tải lên"
                    ),
                ),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="apptimtruonghoc.album",
                        verbose_name="Album",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ảnh",
                "verbose_name_plural": "Các Ảnh",
            },
        ),
        migrations.CreateModel(
            name="AllMajorOfAllSchool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "all_major_id",
                    models.CharField(max_length=255, verbose_name="Mã ngành"),
                ),
                ("name", models.TextField(verbose_name="Tên ngành")),
                (
                    "short_description",
                    ckeditor.fields.RichTextField(
                        blank=True, null=True, verbose_name="Mô tả của ngành chung"
                    ),
                ),
                (
                    "training_duration",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Thời lượng đào tạo",
                    ),
                ),
                (
                    "job",
                    ckeditor.fields.RichTextField(
                        blank=True, null=True, verbose_name="Việc làm sau khi học"
                    ),
                ),
                (
                    "suitable",
                    ckeditor.fields.RichTextField(
                        blank=True, null=True, verbose_name="Tố chất phù hợp"
                    ),
                ),
                (
                    "program",
                    ckeditor.fields.RichTextField(
                        blank=True, null=True, verbose_name="Chương trình học"
                    ),
                ),
                (
                    "salary",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Thu nhập trung bình",
                    ),
                ),
                (
                    "cover",
                    models.CharField(
                        blank=True, max_length=1000, null=True, verbose_name="Ảnh bìa"
                    ),
                ),
                (
                    "tuition_fee_per_year",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Khoảng học phí ngành/năm",
                    ),
                ),
                (
                    "note",
                    ckeditor.fields.RichTextField(
                        blank=True, null=True, verbose_name="Ghi chú"
                    ),
                ),
                (
                    "opportunities",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Cơ hội việc làm của ngành"
                    ),
                ),
                (
                    "tag",
                    models.CharField(
                        choices=[
                            ("hot", "Ngành hot"),
                            ("find", "Ngành đang thiếu nhân lực"),
                            ("grown", "Ngành có phát triển"),
                            ("push", "Đẩy mạnh"),
                            ("normal", "Bình thường"),
                        ],
                        default="normal",
                        max_length=50,
                        verbose_name="Loại ngành",
                    ),
                ),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_gr",
                        to="apptimtruonghoc.fieldgroup",
                        verbose_name="Thuộc lĩnh vực",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ngành",
                "verbose_name_plural": "Các ngành",
            },
        ),
        migrations.CreateModel(
            name="AdmissionScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(verbose_name="Năm tuyển sinh")),
                ("score", models.FloatField(verbose_name="Điểm chuẩn")),
                (
                    "types",
                    models.CharField(
                        choices=[
                            ("THPT", "Điểm thi THPTQG"),
                            ("HB", "Điểm xét tuyển học bạ"),
                            ("DGNL", "Điểm thi đánh giá năng lực"),
                            ("Khác", "Khác"),
                        ],
                        default="THPT",
                        max_length=50,
                        verbose_name="Loại điểm",
                    ),
                ),
                (
                    "major",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admission_scores",
                        to="apptimtruonghoc.major",
                        verbose_name="Ngành",
                    ),
                ),
            ],
            options={
                "verbose_name": "Điểm chuẩn theo ngành",
                "verbose_name_plural": "Các điểm chuẩn theo ngành",
                "unique_together": {("major", "year")},
            },
        ),
    ]
