# Generated by Django 5.2.4 on 2025-07-31 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apptimtruonghoc", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="school",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Email"
            ),
        ),
    ]
