# Generated by Django 5.2.4 on 2025-08-06 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apptimtruonghoc", "0002_alter_school_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="sex",
            field=models.CharField(
                blank=True,
                choices=[("male", "Nam"), ("female", "Nữ"), ("other", "Khác")],
                max_length=255,
                null=True,
                verbose_name="Giới tính",
            ),
        ),
    ]
